### ISSUE TITLE
Can you upload the C2FNet file somewhere else?

### ISSUE THREAD

**Issue by MagicKey23** [Ben57882/C2FNet-TSCVT#3]
Hello,
I try to download the file but it is not in English and require register to download!

**Comment by MagicKey23** [comment]
Anyway, I don't need the pre-trained anymore. I was able to set up my custom training. Thank you for your execellent work!

**Comment by supergengchen** [comment]
Hi, thanks for raising this question. I'm looping in Mr. Sijie Liu, who is the co-first author of this work. He could provide you more details.

Sijie, please help to answer the question. Thanks.

Best,
Geng Chen
